concatenate(), vstack(), hstack()

In [1]:
import numpy as np

a = np.arange(11,19).reshape(2,4)
b = np.arange(12).reshape(3,4)
c = np.arange(8).reshape(2,4)
d = np.array([0,1,2,3]) 

In [2]:
print(a.shape,b.shape)

(2, 4) (3, 4)


In [3]:
np.concatenate((a,b)) # 기본 axis = 0 행으로 각 배열을 더함

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
np.vstack((a,b))  #concatenate axis = 0 행방향 (위에서 아래)

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
np.hstack((a,b)) # 2행과 3열이 같지않기 때문에 안됌 

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [ ]:
np.hstack((a,c)) # 열기반 좌 ->우 

array([[11, 12, 13, 14,  0,  1,  2,  3],
       [15, 16, 17, 18,  4,  5,  6,  7]])

r_c_ Class,     column_stack()

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[10, 20, 30], [40, 50, 60]])
a, b, c, d

(array([1, 2, 3]),
 array([10, 20, 30]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[10, 20, 30],
        [40, 50, 60]]))

In [ ]:
print(np.r_[a,b]) # 행기반 합치기 axis = 1  1차원 일 때

print(np.c_[a,b]) # 열방향으로 각각  1차원 일 때
print(np.r_[c,d])
print(np.c_[c,d])

[ 1  2  3 10 20 30]
[[ 1 10]
 [ 2 20]
 [ 3 30]]
[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]
[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]


In [ ]:
np.column_stack([c,d]) # == np.c_[a,b]

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [ ]:
np.column_stack([c.flatten(),d.flatten()])

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40],
       [ 5, 50],
       [ 6, 60]])